FROM centos:7
MAINTAINER <jimmy.ppy@gmail.com>
LABEL Vendor="Echosens" \
      Version=2.4.6-40


RUN yum -y --setopt=tsflags=nodocs update && \
    yum -y --setopt=tsflags=nodocs install httpd && \
    yum -y --setopt=tsflags=nodocs install php php-mysql && \
    yum clean all

ADD index.php /var/www/html/index.php

EXPOSE 80

# Simple startup script to avoid some issues observed with container restart
ADD run-httpd.sh /run-httpd.sh
RUN chmod -v +x /run-httpd.sh

CMD ["/run-httpd.sh"]